Feature/about us
thecodersguilduk/tcg_site pull request #32
Opened 2020-09-19 22:58 UTC by Jurate-m

Ticket : https://trello.com/c/fGVEUnU8/49-about-us
  - Mobile and Desktop layouts
  - Skipped mobile slider for available apprenticeships (had troubles making it work with Slick slider; Also there's only one apprenticeship scheme available (currently)) - will come back to it asasp;

2020-09-19 22:59 UTC, Jurate-m commented
![](https://github.trello.services/images/mini-trello-icon.png) [About us](https://trello.com/c/fGVEUnU8/49-about-us)

2020-09-20 08:39 UTC, crispinread requested changes
looking really good thanks :)

MIssion and vision look a bit off tho not 50/50 and mabe bit wider than designs? Did not test properly tho just on my machine 13.3-inch MB pro (2560 x 1600) chrome latest

There is a conflict that I can't look into rn bcs kids :D

2020-09-20 11:27 UTC, Jurate-m commented
There was a missing space between class names which resulted  in breaking mission and vision layout - now fixed; Merge conflict resolved.

2020-09-20 17:02 UTC, crispinread approved these changes

2020-09-20 17:03 UTC, merged